### ISSUE TITLE
session_server requires nightly version of Rust

### ISSUE THREAD

**Issue by Abergard** [NadzwyczajnaGrupaRobocza/poker#4]
Do we want to use and requires the nightly version of Rust?

> error: failed to run custom build command for `pear_codegen v0.1.2`
> 
> Caused by:
>   process didn't exit successfully: `w:\poker\session_server\target\debug\build\pear_codegen-90e608710b40a7a2\build-script-build` (exit code: 101)
> --- stderr
> Error: Pear requires a nightly or dev version of Rust.
> Installed version is: 1.44.0 (2020-06-01). Minimum required: 1.31.0-nightly (2018-10-05).

**Comment by lukasz-m-maciejewski** [comment]
Yeah, sorry, should have documented that. Rocket is - as far as I could tell - the most mature web framework for rust and using nightly version is a hard requirement there: https://rocket.rs/v0.4/guide/getting-started/#installing-rust
There may be an ocasional breaking change in the language with nightly, but so what? If it happens, we'll have to refactor and learn something new about the language - it's not like we have money on the line. ;-)
